version: '3.7'
services:
  php:
    image: 'defaultvalue/php:8.2-development'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - ADDITIONAL_PATH=/usr/local/go/bin
      - PHP_IDE_CONFIG=serverName=magento.shop.ua
  mailhog:
    image: 'mailhog/mailhog:v1.0.1'
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mh-prod-magento-shop-ua-http.rule=Host(`mh-prod-magento.shop.ua`)
      - traefik.http.routers.mh-prod-magento-shop-ua-http.entrypoints=http
      - traefik.http.services.mh-prod-magento-shop-ua-http.loadbalancer.server.port=8025
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.pma-prod-magento-shop-ua-http.rule=Host(`pma-prod-magento.shop.ua`)
      - traefik.http.routers.pma-prod-magento-shop-ua-http.entrypoints=http
    depends_on:
      - mysql
    environment:
      PMA_HOSTS: mysql
      PMA_USER: magento_user
      PMA_PASSWORD: 'aD2.c<M&B+-n*lWn'
      PMA_DATABASE: magento_db
      PMA_ABSOLUTE_URI: 'http://pma-prod-magento.shop.ua/'
    volumes:
      - /sessions
